apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fastapi-starter
data:
  ENVIRONMENT: "development"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  CORS_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"
